spring:
  profiles:
    active: mysql

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      
logging:
  level:
    root: ERROR #어느정도 로그 수준은 설정 가능. 규모가 커지고 세부설정이 필요하다면 logback.xml
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%4L] - %m%n"